### ISSUE TITLE
Week 9 ready for grading!

### ISSUE THREAD

**Issue by jsummerfield-matc** [madisoncollege-it-programs/python-scripting-jsummerfield-matc#10]

**Comment by cethenmc** [comment]
Pretty good.  Recording 7 of 8 for now.  Your main function in f2c.py said to print the result.  Please reply to this Issue ticket when you pushed the correction to GitHub.

- Create a main function that calls the convert_temp() function with an argument of 32.
- **_Print the result_** of the function.

**Comment by cethenmc** [comment]
I will also add that the tempconversion.py was intended to be run through the "main()" function, which is why the part title looks like this:  "Script 2 - Temp Conversion (**Main**)."  It was not super clear, so I am not deducting points.  However, since you are modifying the other pieces, you may want to consider modifying your tempconversion.py script to run that way.

**Comment by cethenmc** [comment]
Now 8 of 8
