### ISSUE TITLE
Week 3 Assignment Ready for grading!

### ISSUE THREAD

**Issue by jsummerfield-matc** [madisoncollege-it-programs/python-scripting-jsummerfield-matc#2]

**Comment by cethenmc** [comment]
Hi, Jamie.  Please correct this assignment and reply to this issue when you have pushed your corrected script to Git Hub.  You forgot punctuation (#3), chose the wrong case for some letters (#3, #4, #6, #7), went to the incorrect decimal (#9), missed spaces (#12 and #13).  It may help you to **download** the lab's Word document so that you can count the spaces.  Please be more careful, as I will deduct points beginning in Week 4.  Thanks. ~Chris

**Comment by jsummerfield-matc** [comment]
Fixed the issues in those areas, i think i hard spaced the whole : ^10s section of code on the #13 but i saw 10 $ fills for 12 so i left it as it was but made sure i had the correct spacing. Hope its okay!

**Comment by cethenmc** [comment]
Hi, Jamie.  You still forgot the space between the "][" in #12 and 13, but I will let that slide this time.  For example:

- [   deR    ][  Green   ]
- vs
- [   deR    ] [  Green   ]
