### ISSUE TITLE
midterm 2 Jpark Complete

### ISSUE THREAD

**Issue by jsummerfield-matc** [madisoncollege-it-programs/python-scripting-jsummerfield-matc#7]

**Comment by cethenmc** [comment]
Thanks for putting in a very solid effort on this part of the midterm.  The first part I analyze is program execution.  When I select reboot and shutdown, I get the reboot/shutdown clause correctly, but I get the Lysine Contingency line, as well.  at pt).  Next, I look in the code.  On line 14, you have hardcoded the username and the password instead of comparing to the library entries (2 pts).  In lines 18 - 23, you have done more unnecessary hardcoding.  Those three could have consolidated to the same if statement using the dictionary, without any hardcoding (2 pts).  Lastly, I will mention that you could have saved a few lines and a while loop in printing 25 times.  You achieved the requirement, so no point deduction there.  However, good for you to know. Score 29/33.
